USE Bankbals2
GO

DROP TABLE DK_F101_PIVOT
DROP TABLE DK_F134_PIVOT
DROP TABLE DK_F123_PIVOT
DROP TABLE DK_F135_PIVOT
DROP TABLE DK_F102_PIVOT

GO

DROP PROCEDURE CALC_DK_F101_PIVOT_DATE
DROP PROCEDURE CALC_DK_F134_PIVOT_DATE
DROP PROCEDURE CALC_DK_F135_PIVOT_DATE
DROP PROCEDURE CALC_DK_F123_PIVOT_DATE
DROP PROCEDURE CALC_DK_F102_PIVOT_DATE

GO

DROP FUNCTION BB_DATA101_R
DROP FUNCTION BB_DATA102_R
DROP FUNCTION BB_DATA123_R
DROP FUNCTION BB_DATA134_R
DROP FUNCTION BB_DATA135_R

DROP FUNCTION BB_DATA101
DROP FUNCTION BB_DATA102
DROP FUNCTION BB_DATA123
DROP FUNCTION BB_DATA134
DROP FUNCTION BB_DATA135

DROP FUNCTION XL_ITEMS_FULLLIST_101
DROP FUNCTION XL_ITEMS_FULLLIST_102
DROP FUNCTION XL_ITEMS_FULLLIST_123
DROP FUNCTION XL_ITEMS_FULLLIST_134
DROP FUNCTION XL_ITEMS_FULLLIST_135

DROP FUNCTION XL_ITEMS_DATA101_R
DROP FUNCTION XL_ITEMS_DATA102_R
DROP FUNCTION XL_ITEMS_DATA123_R
DROP FUNCTION XL_ITEMS_DATA134_R
DROP FUNCTION XL_ITEMS_DATA135_R

DROP FUNCTION XL_ITEMS_DATA101
DROP FUNCTION XL_ITEMS_DATA102
DROP FUNCTION XL_ITEMS_DATA123
DROP FUNCTION XL_ITEMS_DATA134
DROP FUNCTION XL_ITEMS_DATA135

DROP FUNCTION BB_VIEW_DATA101
DROP FUNCTION BB_VIEW_DATA102
DROP FUNCTION BB_VIEW_DATA123
DROP FUNCTION BB_VIEW_DATA134
DROP FUNCTION BB_VIEW_DATA135

DROP FUNCTION XLS_DATA101_UNPIVOT
DROP FUNCTION XLS_DATA102_UNPIVOT
DROP FUNCTION XLS_DATA123_UNPIVOT
DROP FUNCTION XLS_DATA134_UNPIVOT
DROP FUNCTION XLS_DATA135_UNPIVOT

GO

ALTER PROCEDURE [dbo].[CALC_DK_F135_ALL] @STARTDATE DATE=NULL, @FINISHDATE DATE=NULL AS
SET NOCOUNT ON
DECLARE @DATE DATE
DECLARE @NEWAGE DATE = (SELECT NewAgeDate FROM NEWAGE_DATE)
PRINT('CALC ALL F135')

DECLARE IndC CURSOR DYNAMIC FOR 
SELECT DATE FROM A_DATE WHERE DATE>=@NEWAGE AND DATE>=ISNULL(@STARTDATE, DATE) AND DATE<=ISNULL(@FINISHDATE, DATE) 
ORDER BY DATE

OPEN IndC
FETCH FIRST FROM IndC INTO @DATE
WHILE @@FETCH_STATUS = 0 
BEGIN
	EXEC CALC_DK_F135_DATE @DATE
	--EXEC CALC_DK_F135_PIVOT_DATE @DATE
	FETCH NEXT FROM IndC INTO @DATE
END
CLOSE IndC
DEALLOCATE IndC

GO

ALTER PROCEDURE [dbo].[CALC_DK_F134_ALL]  @STARTDATE DATE=NULL, @FINISHDATE DATE=NULL AS
SET NOCOUNT ON
DECLARE @DATE DATE
DECLARE @NEWAGE DATE = (SELECT NewAgeDate FROM NEWAGE_DATE)
PRINT('CALC ALL F134')

DECLARE IndC CURSOR DYNAMIC FOR 
SELECT DATE FROM A_DATE WHERE DATE>=@NEWAGE AND DATE>=ISNULL(@STARTDATE, DATE) AND DATE<=ISNULL(@FINISHDATE, DATE)
ORDER BY DATE

OPEN IndC
FETCH FIRST FROM IndC INTO @DATE
WHILE @@FETCH_STATUS = 0 
BEGIN
	EXEC CALC_DK_F134_DATE @DATE
	--EXEC CALC_DK_F134_PIVOT_DATE @DATE
	FETCH NEXT FROM IndC INTO @DATE
END
CLOSE IndC
DEALLOCATE IndC

GO

ALTER PROCEDURE [dbo].[CALC_DK_F102_ALL] @STARTDATE DATE=NULL, @FINISHDATE DATE=NULL AS
SET NOCOUNT ON
DECLARE @DATE DATE
DECLARE @NEWAGE DATE = (SELECT NewAgeDate FROM NEWAGE_DATE)
PRINT('CALC ALL F102')

DECLARE IndC CURSOR DYNAMIC FOR 
SELECT DATE FROM A_DATE WHERE DATE>=@NEWAGE AND IsQuartal =1 AND DATE>=ISNULL(@STARTDATE, DATE) AND DATE<=ISNULL(@FINISHDATE, DATE)
ORDER BY DATE

OPEN IndC
FETCH FIRST FROM IndC INTO @DATE
WHILE @@FETCH_STATUS = 0 
BEGIN
	EXEC CALC_DK_F102_DATE @DATE
	--EXEC CALC_DK_F102_PIVOT_DATE @DATE
	FETCH NEXT FROM IndC INTO @DATE
END
CLOSE IndC
DEALLOCATE IndC

GO

ALTER PROCEDURE [dbo].[CALC_DK_F101_ALL] @STARTDATE DATE=NULL, @FINISHDATE DATE=NULL AS
SET NOCOUNT ON
DECLARE @DATE DATE
DECLARE @NEWAGE DATE = (SELECT NewAgeDate FROM NEWAGE_DATE)
PRINT('CALC ALL F101')

DECLARE IndC CURSOR DYNAMIC FOR 
SELECT DATE FROM A_DATE WHERE DATE>=@NEWAGE AND DATE>=ISNULL(@STARTDATE, DATE) AND DATE<=ISNULL(@FINISHDATE, DATE)
ORDER BY DATE

OPEN IndC
FETCH FIRST FROM IndC INTO @DATE
WHILE @@FETCH_STATUS = 0 
BEGIN
	EXEC CALC_DK_F101_DATE @DATE
	--EXEC CALC_DK_F101_PIVOT_DATE @DATE
	EXEC CALC_DK_BANKS_COMP_DATE @DATE
	EXEC CALC_DK_F101_STAT_DATE @DATE
	FETCH NEXT FROM IndC INTO @DATE
END
CLOSE IndC
DEALLOCATE IndC

GO

ALTER PROCEDURE [dbo].[CALC_DK_F123_ALL]  @STARTDATE DATE=NULL, @FINISHDATE DATE=NULL AS
SET NOCOUNT ON
DECLARE @DATE DATE
DECLARE @NEWAGE DATE = (SELECT NewAgeDate FROM NEWAGE_DATE)
PRINT('CALC ALL F123')

DECLARE IndC CURSOR DYNAMIC FOR 
SELECT DATE FROM A_DATE WHERE DATE>=@NEWAGE AND DATE>=ISNULL(@STARTDATE, DATE) AND DATE<=ISNULL(@FINISHDATE, DATE)
ORDER BY DATE

OPEN IndC
FETCH FIRST FROM IndC INTO @DATE
WHILE @@FETCH_STATUS = 0 
BEGIN
	EXEC CALC_DK_F123_DATE @DATE
	--EXEC CALC_DK_F123_PIVOT_DATE @DATE
	FETCH NEXT FROM IndC INTO @DATE
END
CLOSE IndC
DEALLOCATE IndC

GO

ALTER PROCEDURE [dbo].[CALC_DK_ALL] AS
SET NOCOUNT ON
DECLARE @DATE DATE
DECLARE @NEWAGE DATE = (SELECT NewAgeDate FROM NEWAGE_DATE)

EXEC FILL_A_DATE
EXEC MAKE_SOURCELIST_F101
EXEC MAKE_SOURCELIST_F102
EXEC MAKE_SOURCELIST_F123
EXEC MAKE_SOURCELIST_F134
EXEC MAKE_SOURCELIST_F135
EXEC FILL_A_DATE

DECLARE IndC CURSOR DYNAMIC FOR 
SELECT DATE FROM A_DATE WHERE DATE>=@NEWAGE 
ORDER BY DATE	
	
OPEN IndC
FETCH FIRST FROM IndC INTO @DATE
WHILE @@FETCH_STATUS = 0 
BEGIN
	PRINT @DATE
	EXEC CALC_DK_F101_DATE @DATE
	EXEC CALC_DK_F101_STAT_DATE @DATE
	EXEC CALC_DK_BANKS_COMP_DATE @DATE
	EXEC CALC_DK_F102_DATE @DATE
	EXEC CALC_DK_F123_DATE @DATE
	EXEC CALC_DK_F134_DATE @DATE
	EXEC CALC_DK_F135_DATE @DATE
	FETCH NEXT FROM IndC INTO @DATE
END
CLOSE IndC
DEALLOCATE IndC

EXEC CALC_DK_AGG_ALL
EXEC MAKE_HELP

GO

ALTER PROCEDURE [dbo].[CLEAN_ALL_DATA_WEB]
AS

TRUNCATE TABLE DK_F101
TRUNCATE TABLE DK_F101_TOCUR
TRUNCATE TABLE DK_F101_STAT
TRUNCATE TABLE DK_F102
TRUNCATE TABLE DK_F123
TRUNCATE TABLE DK_F134
TRUNCATE TABLE DK_F135
TRUNCATE TABLE DK_BANKS_COMP
TRUNCATE TABLE DK_F101A
TRUNCATE TABLE DK_F101A_TOCUR
TRUNCATE TABLE DK_F102A
TRUNCATE TABLE DK_TOPBANKS
TRUNCATE TABLE W_HELP

GO

ALTER PROCEDURE [dbo].[CALC_DK_AGG_ALL] AS
SET NOCOUNT ON

DECLARE @DATE DATE
SET @DATE = DBO.CALC_DATEID2DATE((SELECT MAX(DateID) FROM dbo.DK_F101))

EXEC CALC_W_AGG_COMP @DATE

EXEC dbo.CALC_DK_F101_AGG_ALL
EXEC dbo.CALC_DK_F102_AGG_ALL
EXEC dbo.CALC_DK_F134_AGG_ALL

GO

ALTER VIEW [dbo].[NEWAGE_DATE]
AS
SELECT CAST('2009-01-01' AS DATE) AS NewAgeDate

GO