USE BankBals2
GO

EXEC CLEAN_ALL_DATA_WEB
GO


TRUNCATE TABLE DI_CBR_BALS_F101_DATA_TEMP
TRUNCATE TABLE DI_CBR_BALS_F102_DATA_TEMP
TRUNCATE TABLE DI_CBR_BALS_F134_DATA_TEMP
TRUNCATE TABLE DI_CBR_BALS_F123_DATA_TEMP

DECLARE @NEWAGEDATE DATE = (SELECT NewAgeDate FROM dbo.NEWAGE_DATE)

DELETE FROM DI_CBR_BALS_F101_DATA WHERE Date < @NEWAGEDATE OR ID >= 98000
DELETE FROM DI_MBK_BALS_F101_DATA WHERE Date < @NEWAGEDATE OR ID >= 98000

DELETE FROM DI_CBR_BALS_F102_DATA WHERE Date < @NEWAGEDATE
DELETE FROM DI_MBK_BALS_F102_DATA WHERE Date < @NEWAGEDATE

DELETE FROM DI_CBR_BALS_F123_DATA WHERE Date < @NEWAGEDATE

DELETE FROM DI_CBR_BALS_F134_DATA WHERE Date < @NEWAGEDATE

DELETE FROM DI_CBR_BALS_F135_DATA_ACC WHERE Date < @NEWAGEDATE
DELETE FROM DI_CBR_BALS_F135_DATA_CAL WHERE Date < @NEWAGEDATE
DELETE FROM DI_CBR_BALS_F135_DATA_FIG WHERE Date < @NEWAGEDATE
DELETE FROM DI_CBR_BALS_F135_DATA_FOUL WHERE Date < @NEWAGEDATE
DELETE FROM DI_CBR_BALS_F135_DATA_NORM WHERE Date < @NEWAGEDATE

GO

IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = N'GPB\ark22')
DROP USER [GPB\ark22]

GO

IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = N'GPB\ark23')
DROP USER [GPB\ark23]

GO

IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = N'GPB\gpbu0215')
DROP USER [GPB\gpbu0215]

GO

IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = N'webdeveloper')
DROP USER [webdeveloper]

GO

/*========================  S H R I N K   A L L   F I L E S  ===============================*/
DECLARE @SQL NVARCHAR(MAX)
DECLARE @BigSQL NVARCHAR(MAX)
DECLARE @file_name NVARCHAR(50) 
DECLARE @file_id INT

DECLARE files_cursor CURSOR FOR 
SELECT file_id, name FROM master.sys.master_files
WHERE database_id = ( 
	SELECT database_id FROM master.sys.databases WHERE Name = 'BankBals2'
)

OPEN files_cursor

FETCH NEXT FROM files_cursor
INTO @file_id, @file_name

WHILE @@FETCH_STATUS = 0
BEGIN

    SET @sql = 'DBCC SHRINKFILE (''''' + @file_name + ''''', 10) WITH NO_INFOMSGS'
    --PRINT @SQL
    
    SET @BigSQL = 'USE [BankBals2]; EXEC sp_executesql N''' + @sql + '''';
    --PRINT @BigSQL 
    EXEC (@BigSQL)
        
    FETCH NEXT FROM files_cursor 
    INTO @file_id, @file_name
END 
CLOSE files_cursor
DEALLOCATE files_cursor

