#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.BankBals.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BankBals2")]
	public partial class BankBalsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertA_VIEW(A_VIEW instance);
    partial void UpdateA_VIEW(A_VIEW instance);
    partial void DeleteA_VIEW(A_VIEW instance);
    partial void InsertA_PARAM(A_PARAM instance);
    partial void UpdateA_PARAM(A_PARAM instance);
    partial void DeleteA_PARAM(A_PARAM instance);
    partial void InsertA_VIEWS_SET(A_VIEWS_SET instance);
    partial void UpdateA_VIEWS_SET(A_VIEWS_SET instance);
    partial void DeleteA_VIEWS_SET(A_VIEWS_SET instance);
    partial void InsertA_AGGITEMTYPE(A_AGGITEMTYPE instance);
    partial void UpdateA_AGGITEMTYPE(A_AGGITEMTYPE instance);
    partial void DeleteA_AGGITEMTYPE(A_AGGITEMTYPE instance);
    partial void InsertA_BANK(A_BANK instance);
    partial void UpdateA_BANK(A_BANK instance);
    partial void DeleteA_BANK(A_BANK instance);
    partial void InsertA_AGG(A_AGG instance);
    partial void UpdateA_AGG(A_AGG instance);
    partial void DeleteA_AGG(A_AGG instance);
    partial void InsertA_F101_TOCURITEM(A_F101_TOCURITEM instance);
    partial void UpdateA_F101_TOCURITEM(A_F101_TOCURITEM instance);
    partial void DeleteA_F101_TOCURITEM(A_F101_TOCURITEM instance);
    partial void InsertW_AGG_COMP(W_AGG_COMP instance);
    partial void UpdateW_AGG_COMP(W_AGG_COMP instance);
    partial void DeleteW_AGG_COMP(W_AGG_COMP instance);
    partial void InsertA_VIEWS_BANKSPIC(A_VIEWS_BANKSPIC instance);
    partial void UpdateA_VIEWS_BANKSPIC(A_VIEWS_BANKSPIC instance);
    partial void DeleteA_VIEWS_BANKSPIC(A_VIEWS_BANKSPIC instance);
    partial void InsertA_DATE(A_DATE instance);
    partial void UpdateA_DATE(A_DATE instance);
    partial void DeleteA_DATE(A_DATE instance);
    partial void InsertA_VIEWITEM(A_VIEWITEM instance);
    partial void UpdateA_VIEWITEM(A_VIEWITEM instance);
    partial void DeleteA_VIEWITEM(A_VIEWITEM instance);
    #endregion
		
		public BankBalsDataContext() : 
				base(global::www.BankBals.Properties.Settings.Default.BankBals2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BankBalsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BankBalsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BankBalsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BankBalsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<A_VIEW> A_VIEWs
		{
			get
			{
				return this.GetTable<A_VIEW>();
			}
		}
		
		public System.Data.Linq.Table<A_PARAM> A_PARAMs
		{
			get
			{
				return this.GetTable<A_PARAM>();
			}
		}
		
		public System.Data.Linq.Table<A_VIEWS_SET> A_VIEWS_SETs
		{
			get
			{
				return this.GetTable<A_VIEWS_SET>();
			}
		}
		
		public System.Data.Linq.Table<A_AGGITEM> A_AGGITEMs
		{
			get
			{
				return this.GetTable<A_AGGITEM>();
			}
		}
		
		public System.Data.Linq.Table<A_AGGITEMTYPE> A_AGGITEMTYPEs
		{
			get
			{
				return this.GetTable<A_AGGITEMTYPE>();
			}
		}
		
		public System.Data.Linq.Table<A_BANK> A_BANKs
		{
			get
			{
				return this.GetTable<A_BANK>();
			}
		}
		
		public System.Data.Linq.Table<A_AGG> A_AGGs
		{
			get
			{
				return this.GetTable<A_AGG>();
			}
		}
		
		public System.Data.Linq.Table<A_BANKS_ALL> A_BANKS_ALLs
		{
			get
			{
				return this.GetTable<A_BANKS_ALL>();
			}
		}
		
		public System.Data.Linq.Table<A_VIEWITEMS_ALL> A_VIEWITEMS_ALLs
		{
			get
			{
				return this.GetTable<A_VIEWITEMS_ALL>();
			}
		}
		
		public System.Data.Linq.Table<A_F101_TOCURITEM> A_F101_TOCURITEMs
		{
			get
			{
				return this.GetTable<A_F101_TOCURITEM>();
			}
		}
		
		public System.Data.Linq.Table<A_VIEWITEMS_COMPARE> A_VIEWITEMS_COMPAREs
		{
			get
			{
				return this.GetTable<A_VIEWITEMS_COMPARE>();
			}
		}
		
		public System.Data.Linq.Table<A_2X2CHARTS_VIEW> A_2X2CHARTS_VIEWs
		{
			get
			{
				return this.GetTable<A_2X2CHARTS_VIEW>();
			}
		}
		
		public System.Data.Linq.Table<W_AGG_COMP> W_AGG_COMPs
		{
			get
			{
				return this.GetTable<W_AGG_COMP>();
			}
		}
		
		public System.Data.Linq.Table<A_VIEWS_BANKSPIC> A_VIEWS_BANKSPICs
		{
			get
			{
				return this.GetTable<A_VIEWS_BANKSPIC>();
			}
		}
		
		public System.Data.Linq.Table<A_DATE> A_DATEs
		{
			get
			{
				return this.GetTable<A_DATE>();
			}
		}
		
		public System.Data.Linq.Table<A_VIEWITEM> A_VIEWITEMs
		{
			get
			{
				return this.GetTable<A_VIEWITEM>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_VIEWS")]
	public partial class A_VIEW : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ViewID;
		
		private string _Ticker;
		
		private string _ViewNameRus;
		
		private string _ViewNameEng;
		
		private int _Form;
		
		private string _DescFilterCol;
		
		private string _DescFilterCaption;
		
		private string _DescFilterMask;
		
		private string _DescFilterRow;
		
		private bool _IsHidden;
		
		private int _OrderNum;
		
		private bool _IsAdvanced;
		
		private EntitySet<A_VIEWS_SET> _A_VIEWS_SETs;
		
		private EntitySet<A_VIEWITEM> _A_VIEWITEMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnViewIDChanging(int value);
    partial void OnViewIDChanged();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    partial void OnViewNameRusChanging(string value);
    partial void OnViewNameRusChanged();
    partial void OnViewNameEngChanging(string value);
    partial void OnViewNameEngChanged();
    partial void OnFormChanging(int value);
    partial void OnFormChanged();
    partial void OnDescFilterColChanging(string value);
    partial void OnDescFilterColChanged();
    partial void OnDescFilterCaptionChanging(string value);
    partial void OnDescFilterCaptionChanged();
    partial void OnDescFilterMaskChanging(string value);
    partial void OnDescFilterMaskChanged();
    partial void OnDescFilterRowChanging(string value);
    partial void OnDescFilterRowChanged();
    partial void OnIsHiddenChanging(bool value);
    partial void OnIsHiddenChanged();
    partial void OnOrderNumChanging(int value);
    partial void OnOrderNumChanged();
    partial void OnIsAdvancedChanging(bool value);
    partial void OnIsAdvancedChanged();
    #endregion
		
		public A_VIEW()
		{
			this._A_VIEWS_SETs = new EntitySet<A_VIEWS_SET>(new Action<A_VIEWS_SET>(this.attach_A_VIEWS_SETs), new Action<A_VIEWS_SET>(this.detach_A_VIEWS_SETs));
			this._A_VIEWITEMs = new EntitySet<A_VIEWITEM>(new Action<A_VIEWITEM>(this.attach_A_VIEWITEMs), new Action<A_VIEWITEM>(this.detach_A_VIEWITEMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ViewID
		{
			get
			{
				return this._ViewID;
			}
			set
			{
				if ((this._ViewID != value))
				{
					this.OnViewIDChanging(value);
					this.SendPropertyChanging();
					this._ViewID = value;
					this.SendPropertyChanged("ViewID");
					this.OnViewIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewNameRus", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ViewNameRus
		{
			get
			{
				return this._ViewNameRus;
			}
			set
			{
				if ((this._ViewNameRus != value))
				{
					this.OnViewNameRusChanging(value);
					this.SendPropertyChanging();
					this._ViewNameRus = value;
					this.SendPropertyChanged("ViewNameRus");
					this.OnViewNameRusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewNameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ViewNameEng
		{
			get
			{
				return this._ViewNameEng;
			}
			set
			{
				if ((this._ViewNameEng != value))
				{
					this.OnViewNameEngChanging(value);
					this.SendPropertyChanging();
					this._ViewNameEng = value;
					this.SendPropertyChanged("ViewNameEng");
					this.OnViewNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="Int NOT NULL")]
		public int Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this.OnFormChanging(value);
					this.SendPropertyChanging();
					this._Form = value;
					this.SendPropertyChanged("Form");
					this.OnFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescFilterCol", DbType="NVarChar(4000)")]
		public string DescFilterCol
		{
			get
			{
				return this._DescFilterCol;
			}
			set
			{
				if ((this._DescFilterCol != value))
				{
					this.OnDescFilterColChanging(value);
					this.SendPropertyChanging();
					this._DescFilterCol = value;
					this.SendPropertyChanged("DescFilterCol");
					this.OnDescFilterColChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescFilterCaption", DbType="NVarChar(4000)")]
		public string DescFilterCaption
		{
			get
			{
				return this._DescFilterCaption;
			}
			set
			{
				if ((this._DescFilterCaption != value))
				{
					this.OnDescFilterCaptionChanging(value);
					this.SendPropertyChanging();
					this._DescFilterCaption = value;
					this.SendPropertyChanged("DescFilterCaption");
					this.OnDescFilterCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescFilterMask", DbType="NVarChar(4000)")]
		public string DescFilterMask
		{
			get
			{
				return this._DescFilterMask;
			}
			set
			{
				if ((this._DescFilterMask != value))
				{
					this.OnDescFilterMaskChanging(value);
					this.SendPropertyChanging();
					this._DescFilterMask = value;
					this.SendPropertyChanged("DescFilterMask");
					this.OnDescFilterMaskChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescFilterRow", DbType="NVarChar(4000)")]
		public string DescFilterRow
		{
			get
			{
				return this._DescFilterRow;
			}
			set
			{
				if ((this._DescFilterRow != value))
				{
					this.OnDescFilterRowChanging(value);
					this.SendPropertyChanging();
					this._DescFilterRow = value;
					this.SendPropertyChanged("DescFilterRow");
					this.OnDescFilterRowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHidden", DbType="Bit NOT NULL")]
		public bool IsHidden
		{
			get
			{
				return this._IsHidden;
			}
			set
			{
				if ((this._IsHidden != value))
				{
					this.OnIsHiddenChanging(value);
					this.SendPropertyChanging();
					this._IsHidden = value;
					this.SendPropertyChanged("IsHidden");
					this.OnIsHiddenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNum", DbType="Int NOT NULL")]
		public int OrderNum
		{
			get
			{
				return this._OrderNum;
			}
			set
			{
				if ((this._OrderNum != value))
				{
					this.OnOrderNumChanging(value);
					this.SendPropertyChanging();
					this._OrderNum = value;
					this.SendPropertyChanged("OrderNum");
					this.OnOrderNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdvanced", DbType="Bit NOT NULL")]
		public bool IsAdvanced
		{
			get
			{
				return this._IsAdvanced;
			}
			set
			{
				if ((this._IsAdvanced != value))
				{
					this.OnIsAdvancedChanging(value);
					this.SendPropertyChanging();
					this._IsAdvanced = value;
					this.SendPropertyChanged("IsAdvanced");
					this.OnIsAdvancedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_VIEW_A_VIEWS_SET", Storage="_A_VIEWS_SETs", ThisKey="ViewID", OtherKey="ViewID")]
		public EntitySet<A_VIEWS_SET> A_VIEWS_SETs
		{
			get
			{
				return this._A_VIEWS_SETs;
			}
			set
			{
				this._A_VIEWS_SETs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_VIEW_A_VIEWITEM", Storage="_A_VIEWITEMs", ThisKey="ViewID", OtherKey="ViewID")]
		public EntitySet<A_VIEWITEM> A_VIEWITEMs
		{
			get
			{
				return this._A_VIEWITEMs;
			}
			set
			{
				this._A_VIEWITEMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_A_VIEWS_SETs(A_VIEWS_SET entity)
		{
			this.SendPropertyChanging();
			entity.A_VIEW = this;
		}
		
		private void detach_A_VIEWS_SETs(A_VIEWS_SET entity)
		{
			this.SendPropertyChanging();
			entity.A_VIEW = null;
		}
		
		private void attach_A_VIEWITEMs(A_VIEWITEM entity)
		{
			this.SendPropertyChanging();
			entity.A_VIEW = this;
		}
		
		private void detach_A_VIEWITEMs(A_VIEWITEM entity)
		{
			this.SendPropertyChanging();
			entity.A_VIEW = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_PARAMS")]
	public partial class A_PARAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ParID;
		
		private string _Ticker;
		
		private string _NameRus;
		
		private string _NameEng;
		
		private string _WebRus;
		
		private string _WebEng;
		
		private bool _F101;
		
		private bool _F102;
		
		private bool _F123;
		
		private bool _F134;
		
		private bool _F135;
		
		private bool _IsHasRank;
		
		private bool _IsRatio;
		
		private System.Nullable<int> _ChgParID;
		
		private bool _IsMain;
		
		private bool _IsChange;
		
		private EntitySet<A_VIEWS_SET> _A_VIEWS_SETs;
		
		private EntitySet<A_VIEWS_SET> _A_VIEWS_SETs1;
		
		private EntitySet<A_VIEWITEM> _A_VIEWITEMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnParIDChanging(int value);
    partial void OnParIDChanged();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    partial void OnNameRusChanging(string value);
    partial void OnNameRusChanged();
    partial void OnNameEngChanging(string value);
    partial void OnNameEngChanged();
    partial void OnWebRusChanging(string value);
    partial void OnWebRusChanged();
    partial void OnWebEngChanging(string value);
    partial void OnWebEngChanged();
    partial void OnF101Changing(bool value);
    partial void OnF101Changed();
    partial void OnF102Changing(bool value);
    partial void OnF102Changed();
    partial void OnF123Changing(bool value);
    partial void OnF123Changed();
    partial void OnF134Changing(bool value);
    partial void OnF134Changed();
    partial void OnF135Changing(bool value);
    partial void OnF135Changed();
    partial void OnIsHasRankChanging(bool value);
    partial void OnIsHasRankChanged();
    partial void OnIsRatioChanging(bool value);
    partial void OnIsRatioChanged();
    partial void OnChgParIDChanging(System.Nullable<int> value);
    partial void OnChgParIDChanged();
    partial void OnIsMainChanging(bool value);
    partial void OnIsMainChanged();
    partial void OnIsChangeChanging(bool value);
    partial void OnIsChangeChanged();
    #endregion
		
		public A_PARAM()
		{
			this._A_VIEWS_SETs = new EntitySet<A_VIEWS_SET>(new Action<A_VIEWS_SET>(this.attach_A_VIEWS_SETs), new Action<A_VIEWS_SET>(this.detach_A_VIEWS_SETs));
			this._A_VIEWS_SETs1 = new EntitySet<A_VIEWS_SET>(new Action<A_VIEWS_SET>(this.attach_A_VIEWS_SETs1), new Action<A_VIEWS_SET>(this.detach_A_VIEWS_SETs1));
			this._A_VIEWITEMs = new EntitySet<A_VIEWITEM>(new Action<A_VIEWITEM>(this.attach_A_VIEWITEMs), new Action<A_VIEWITEM>(this.detach_A_VIEWITEMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ParID
		{
			get
			{
				return this._ParID;
			}
			set
			{
				if ((this._ParID != value))
				{
					this.OnParIDChanging(value);
					this.SendPropertyChanging();
					this._ParID = value;
					this.SendPropertyChanged("ParID");
					this.OnParIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRus", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NameRus
		{
			get
			{
				return this._NameRus;
			}
			set
			{
				if ((this._NameRus != value))
				{
					this.OnNameRusChanging(value);
					this.SendPropertyChanging();
					this._NameRus = value;
					this.SendPropertyChanged("NameRus");
					this.OnNameRusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NameEng
		{
			get
			{
				return this._NameEng;
			}
			set
			{
				if ((this._NameEng != value))
				{
					this.OnNameEngChanging(value);
					this.SendPropertyChanging();
					this._NameEng = value;
					this.SendPropertyChanged("NameEng");
					this.OnNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebRus", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string WebRus
		{
			get
			{
				return this._WebRus;
			}
			set
			{
				if ((this._WebRus != value))
				{
					this.OnWebRusChanging(value);
					this.SendPropertyChanging();
					this._WebRus = value;
					this.SendPropertyChanged("WebRus");
					this.OnWebRusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebEng", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string WebEng
		{
			get
			{
				return this._WebEng;
			}
			set
			{
				if ((this._WebEng != value))
				{
					this.OnWebEngChanging(value);
					this.SendPropertyChanging();
					this._WebEng = value;
					this.SendPropertyChanged("WebEng");
					this.OnWebEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F101", DbType="Bit NOT NULL")]
		public bool F101
		{
			get
			{
				return this._F101;
			}
			set
			{
				if ((this._F101 != value))
				{
					this.OnF101Changing(value);
					this.SendPropertyChanging();
					this._F101 = value;
					this.SendPropertyChanged("F101");
					this.OnF101Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F102", DbType="Bit NOT NULL")]
		public bool F102
		{
			get
			{
				return this._F102;
			}
			set
			{
				if ((this._F102 != value))
				{
					this.OnF102Changing(value);
					this.SendPropertyChanging();
					this._F102 = value;
					this.SendPropertyChanged("F102");
					this.OnF102Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F123", DbType="Bit NOT NULL")]
		public bool F123
		{
			get
			{
				return this._F123;
			}
			set
			{
				if ((this._F123 != value))
				{
					this.OnF123Changing(value);
					this.SendPropertyChanging();
					this._F123 = value;
					this.SendPropertyChanged("F123");
					this.OnF123Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F134", DbType="Bit NOT NULL")]
		public bool F134
		{
			get
			{
				return this._F134;
			}
			set
			{
				if ((this._F134 != value))
				{
					this.OnF134Changing(value);
					this.SendPropertyChanging();
					this._F134 = value;
					this.SendPropertyChanged("F134");
					this.OnF134Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F135", DbType="Bit NOT NULL")]
		public bool F135
		{
			get
			{
				return this._F135;
			}
			set
			{
				if ((this._F135 != value))
				{
					this.OnF135Changing(value);
					this.SendPropertyChanging();
					this._F135 = value;
					this.SendPropertyChanged("F135");
					this.OnF135Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHasRank", DbType="Bit NOT NULL")]
		public bool IsHasRank
		{
			get
			{
				return this._IsHasRank;
			}
			set
			{
				if ((this._IsHasRank != value))
				{
					this.OnIsHasRankChanging(value);
					this.SendPropertyChanging();
					this._IsHasRank = value;
					this.SendPropertyChanged("IsHasRank");
					this.OnIsHasRankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRatio", DbType="Bit NOT NULL")]
		public bool IsRatio
		{
			get
			{
				return this._IsRatio;
			}
			set
			{
				if ((this._IsRatio != value))
				{
					this.OnIsRatioChanging(value);
					this.SendPropertyChanging();
					this._IsRatio = value;
					this.SendPropertyChanged("IsRatio");
					this.OnIsRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChgParID", DbType="Int")]
		public System.Nullable<int> ChgParID
		{
			get
			{
				return this._ChgParID;
			}
			set
			{
				if ((this._ChgParID != value))
				{
					this.OnChgParIDChanging(value);
					this.SendPropertyChanging();
					this._ChgParID = value;
					this.SendPropertyChanged("ChgParID");
					this.OnChgParIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMain", DbType="Bit NOT NULL")]
		public bool IsMain
		{
			get
			{
				return this._IsMain;
			}
			set
			{
				if ((this._IsMain != value))
				{
					this.OnIsMainChanging(value);
					this.SendPropertyChanging();
					this._IsMain = value;
					this.SendPropertyChanged("IsMain");
					this.OnIsMainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsChange", DbType="Bit NOT NULL")]
		public bool IsChange
		{
			get
			{
				return this._IsChange;
			}
			set
			{
				if ((this._IsChange != value))
				{
					this.OnIsChangeChanging(value);
					this.SendPropertyChanging();
					this._IsChange = value;
					this.SendPropertyChanged("IsChange");
					this.OnIsChangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_PARAM_A_VIEWS_SET", Storage="_A_VIEWS_SETs", ThisKey="ParID", OtherKey="ParID1")]
		public EntitySet<A_VIEWS_SET> A_VIEWS_SETs
		{
			get
			{
				return this._A_VIEWS_SETs;
			}
			set
			{
				this._A_VIEWS_SETs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_PARAM_A_VIEWS_SET1", Storage="_A_VIEWS_SETs1", ThisKey="ParID", OtherKey="ParID2")]
		public EntitySet<A_VIEWS_SET> A_VIEWS_SETs1
		{
			get
			{
				return this._A_VIEWS_SETs1;
			}
			set
			{
				this._A_VIEWS_SETs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_PARAM_A_VIEWITEM", Storage="_A_VIEWITEMs", ThisKey="ParID", OtherKey="ParID")]
		public EntitySet<A_VIEWITEM> A_VIEWITEMs
		{
			get
			{
				return this._A_VIEWITEMs;
			}
			set
			{
				this._A_VIEWITEMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_A_VIEWS_SETs(A_VIEWS_SET entity)
		{
			this.SendPropertyChanging();
			entity.A_PARAM = this;
		}
		
		private void detach_A_VIEWS_SETs(A_VIEWS_SET entity)
		{
			this.SendPropertyChanging();
			entity.A_PARAM = null;
		}
		
		private void attach_A_VIEWS_SETs1(A_VIEWS_SET entity)
		{
			this.SendPropertyChanging();
			entity.A_PARAM1 = this;
		}
		
		private void detach_A_VIEWS_SETs1(A_VIEWS_SET entity)
		{
			this.SendPropertyChanging();
			entity.A_PARAM1 = null;
		}
		
		private void attach_A_VIEWITEMs(A_VIEWITEM entity)
		{
			this.SendPropertyChanging();
			entity.A_PARAM = this;
		}
		
		private void detach_A_VIEWITEMs(A_VIEWITEM entity)
		{
			this.SendPropertyChanging();
			entity.A_PARAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_VIEWS_SET")]
	public partial class A_VIEWS_SET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SetID;
		
		private int _ViewID;
		
		private int _ParID1;
		
		private System.Nullable<int> _ParID2;
		
		private int _OrderNum;
		
		private EntityRef<A_PARAM> _A_PARAM;
		
		private EntityRef<A_PARAM> _A_PARAM1;
		
		private EntityRef<A_VIEW> _A_VIEW;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSetIDChanging(int value);
    partial void OnSetIDChanged();
    partial void OnViewIDChanging(int value);
    partial void OnViewIDChanged();
    partial void OnParID1Changing(int value);
    partial void OnParID1Changed();
    partial void OnParID2Changing(System.Nullable<int> value);
    partial void OnParID2Changed();
    partial void OnOrderNumChanging(int value);
    partial void OnOrderNumChanged();
    #endregion
		
		public A_VIEWS_SET()
		{
			this._A_PARAM = default(EntityRef<A_PARAM>);
			this._A_PARAM1 = default(EntityRef<A_PARAM>);
			this._A_VIEW = default(EntityRef<A_VIEW>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SetID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SetID
		{
			get
			{
				return this._SetID;
			}
			set
			{
				if ((this._SetID != value))
				{
					this.OnSetIDChanging(value);
					this.SendPropertyChanging();
					this._SetID = value;
					this.SendPropertyChanged("SetID");
					this.OnSetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ViewID
		{
			get
			{
				return this._ViewID;
			}
			set
			{
				if ((this._ViewID != value))
				{
					if (this._A_VIEW.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnViewIDChanging(value);
					this.SendPropertyChanging();
					this._ViewID = value;
					this.SendPropertyChanged("ViewID");
					this.OnViewIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParID1", DbType="Int NOT NULL")]
		public int ParID1
		{
			get
			{
				return this._ParID1;
			}
			set
			{
				if ((this._ParID1 != value))
				{
					if (this._A_PARAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParID1Changing(value);
					this.SendPropertyChanging();
					this._ParID1 = value;
					this.SendPropertyChanged("ParID1");
					this.OnParID1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParID2", DbType="Int")]
		public System.Nullable<int> ParID2
		{
			get
			{
				return this._ParID2;
			}
			set
			{
				if ((this._ParID2 != value))
				{
					if (this._A_PARAM1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParID2Changing(value);
					this.SendPropertyChanging();
					this._ParID2 = value;
					this.SendPropertyChanged("ParID2");
					this.OnParID2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNum", DbType="Int NOT NULL")]
		public int OrderNum
		{
			get
			{
				return this._OrderNum;
			}
			set
			{
				if ((this._OrderNum != value))
				{
					this.OnOrderNumChanging(value);
					this.SendPropertyChanging();
					this._OrderNum = value;
					this.SendPropertyChanged("OrderNum");
					this.OnOrderNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_PARAM_A_VIEWS_SET", Storage="_A_PARAM", ThisKey="ParID1", OtherKey="ParID", IsForeignKey=true)]
		public A_PARAM A_PARAM
		{
			get
			{
				return this._A_PARAM.Entity;
			}
			set
			{
				A_PARAM previousValue = this._A_PARAM.Entity;
				if (((previousValue != value) 
							|| (this._A_PARAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._A_PARAM.Entity = null;
						previousValue.A_VIEWS_SETs.Remove(this);
					}
					this._A_PARAM.Entity = value;
					if ((value != null))
					{
						value.A_VIEWS_SETs.Add(this);
						this._ParID1 = value.ParID;
					}
					else
					{
						this._ParID1 = default(int);
					}
					this.SendPropertyChanged("A_PARAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_PARAM_A_VIEWS_SET1", Storage="_A_PARAM1", ThisKey="ParID2", OtherKey="ParID", IsForeignKey=true)]
		public A_PARAM A_PARAM1
		{
			get
			{
				return this._A_PARAM1.Entity;
			}
			set
			{
				A_PARAM previousValue = this._A_PARAM1.Entity;
				if (((previousValue != value) 
							|| (this._A_PARAM1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._A_PARAM1.Entity = null;
						previousValue.A_VIEWS_SETs1.Remove(this);
					}
					this._A_PARAM1.Entity = value;
					if ((value != null))
					{
						value.A_VIEWS_SETs1.Add(this);
						this._ParID2 = value.ParID;
					}
					else
					{
						this._ParID2 = default(Nullable<int>);
					}
					this.SendPropertyChanged("A_PARAM1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_VIEW_A_VIEWS_SET", Storage="_A_VIEW", ThisKey="ViewID", OtherKey="ViewID", IsForeignKey=true)]
		public A_VIEW A_VIEW
		{
			get
			{
				return this._A_VIEW.Entity;
			}
			set
			{
				A_VIEW previousValue = this._A_VIEW.Entity;
				if (((previousValue != value) 
							|| (this._A_VIEW.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._A_VIEW.Entity = null;
						previousValue.A_VIEWS_SETs.Remove(this);
					}
					this._A_VIEW.Entity = value;
					if ((value != null))
					{
						value.A_VIEWS_SETs.Add(this);
						this._ViewID = value.ViewID;
					}
					else
					{
						this._ViewID = default(int);
					}
					this.SendPropertyChanged("A_VIEW");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_AGGITEMS")]
	public partial class A_AGGITEM
	{
		
		private int _Form;
		
		private int _AggItemID;
		
		private string _Ticker;
		
		private string _ID;
		
		private byte _AggItemTypeID;
		
		private string _NameRus;
		
		private string _NameEng;
		
		private int _OrderNum;
		
		private System.Nullable<bool> _IsDivideByAcc;
		
		private System.Nullable<int> _TickerChecked;
		
		private System.Nullable<bool> _IsTotalAssets;
		
		public A_AGGITEM()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="Int NOT NULL")]
		public int Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this._Form = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AggItemID", DbType="Int NOT NULL")]
		public int AggItemID
		{
			get
			{
				return this._AggItemID;
			}
			set
			{
				if ((this._AggItemID != value))
				{
					this._AggItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this._Ticker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(30)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AggItemTypeID", DbType="TinyInt NOT NULL")]
		public byte AggItemTypeID
		{
			get
			{
				return this._AggItemTypeID;
			}
			set
			{
				if ((this._AggItemTypeID != value))
				{
					this._AggItemTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRus", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NameRus
		{
			get
			{
				return this._NameRus;
			}
			set
			{
				if ((this._NameRus != value))
				{
					this._NameRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NameEng
		{
			get
			{
				return this._NameEng;
			}
			set
			{
				if ((this._NameEng != value))
				{
					this._NameEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNum", DbType="Int NOT NULL")]
		public int OrderNum
		{
			get
			{
				return this._OrderNum;
			}
			set
			{
				if ((this._OrderNum != value))
				{
					this._OrderNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDivideByAcc", DbType="Bit")]
		public System.Nullable<bool> IsDivideByAcc
		{
			get
			{
				return this._IsDivideByAcc;
			}
			set
			{
				if ((this._IsDivideByAcc != value))
				{
					this._IsDivideByAcc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TickerChecked", DbType="Int")]
		public System.Nullable<int> TickerChecked
		{
			get
			{
				return this._TickerChecked;
			}
			set
			{
				if ((this._TickerChecked != value))
				{
					this._TickerChecked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTotalAssets", DbType="Bit")]
		public System.Nullable<bool> IsTotalAssets
		{
			get
			{
				return this._IsTotalAssets;
			}
			set
			{
				if ((this._IsTotalAssets != value))
				{
					this._IsTotalAssets = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_AGGITEMTYPES")]
	public partial class A_AGGITEMTYPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _AggItemTypeID;
		
		private string _NameRus;
		
		private string _NameEng;
		
		private bool _IsRatio;
		
		private string _Comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAggItemTypeIDChanging(byte value);
    partial void OnAggItemTypeIDChanged();
    partial void OnNameRusChanging(string value);
    partial void OnNameRusChanged();
    partial void OnNameEngChanging(string value);
    partial void OnNameEngChanged();
    partial void OnIsRatioChanging(bool value);
    partial void OnIsRatioChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public A_AGGITEMTYPE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AggItemTypeID", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte AggItemTypeID
		{
			get
			{
				return this._AggItemTypeID;
			}
			set
			{
				if ((this._AggItemTypeID != value))
				{
					this.OnAggItemTypeIDChanging(value);
					this.SendPropertyChanging();
					this._AggItemTypeID = value;
					this.SendPropertyChanged("AggItemTypeID");
					this.OnAggItemTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRus", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NameRus
		{
			get
			{
				return this._NameRus;
			}
			set
			{
				if ((this._NameRus != value))
				{
					this.OnNameRusChanging(value);
					this.SendPropertyChanging();
					this._NameRus = value;
					this.SendPropertyChanged("NameRus");
					this.OnNameRusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NameEng
		{
			get
			{
				return this._NameEng;
			}
			set
			{
				if ((this._NameEng != value))
				{
					this.OnNameEngChanging(value);
					this.SendPropertyChanging();
					this._NameEng = value;
					this.SendPropertyChanged("NameEng");
					this.OnNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRatio", DbType="Bit NOT NULL")]
		public bool IsRatio
		{
			get
			{
				return this._IsRatio;
			}
			set
			{
				if ((this._IsRatio != value))
				{
					this.OnIsRatioChanging(value);
					this.SendPropertyChanging();
					this._IsRatio = value;
					this.SendPropertyChanged("IsRatio");
					this.OnIsRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_BANKS")]
	public partial class A_BANK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BankID;
		
		private string _FullName;
		
		private string _FullNameRUS;
		
		private string _FullNameENG;
		
		private int _BankTTypeID;
		
		private bool _IsHidden;
		
		private bool _IsHaveData;
		
		private System.Nullable<int> _IssuerID;
		
		private EntitySet<W_AGG_COMP> _W_AGG_COMPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBankIDChanging(int value);
    partial void OnBankIDChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnFullNameRUSChanging(string value);
    partial void OnFullNameRUSChanged();
    partial void OnFullNameENGChanging(string value);
    partial void OnFullNameENGChanged();
    partial void OnBankTTypeIDChanging(int value);
    partial void OnBankTTypeIDChanged();
    partial void OnIsHiddenChanging(bool value);
    partial void OnIsHiddenChanged();
    partial void OnIsHaveDataChanging(bool value);
    partial void OnIsHaveDataChanged();
    partial void OnIssuerIDChanging(System.Nullable<int> value);
    partial void OnIssuerIDChanged();
    #endregion
		
		public A_BANK()
		{
			this._W_AGG_COMPs = new EntitySet<W_AGG_COMP>(new Action<W_AGG_COMP>(this.attach_W_AGG_COMPs), new Action<W_AGG_COMP>(this.detach_W_AGG_COMPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BankID
		{
			get
			{
				return this._BankID;
			}
			set
			{
				if ((this._BankID != value))
				{
					this.OnBankIDChanging(value);
					this.SendPropertyChanging();
					this._BankID = value;
					this.SendPropertyChanged("BankID");
					this.OnBankIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(150)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameRUS", DbType="NVarChar(150)")]
		public string FullNameRUS
		{
			get
			{
				return this._FullNameRUS;
			}
			set
			{
				if ((this._FullNameRUS != value))
				{
					this.OnFullNameRUSChanging(value);
					this.SendPropertyChanging();
					this._FullNameRUS = value;
					this.SendPropertyChanged("FullNameRUS");
					this.OnFullNameRUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameENG", DbType="NVarChar(150)")]
		public string FullNameENG
		{
			get
			{
				return this._FullNameENG;
			}
			set
			{
				if ((this._FullNameENG != value))
				{
					this.OnFullNameENGChanging(value);
					this.SendPropertyChanging();
					this._FullNameENG = value;
					this.SendPropertyChanged("FullNameENG");
					this.OnFullNameENGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankTTypeID", DbType="Int NOT NULL")]
		public int BankTTypeID
		{
			get
			{
				return this._BankTTypeID;
			}
			set
			{
				if ((this._BankTTypeID != value))
				{
					this.OnBankTTypeIDChanging(value);
					this.SendPropertyChanging();
					this._BankTTypeID = value;
					this.SendPropertyChanged("BankTTypeID");
					this.OnBankTTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHidden", DbType="Bit NOT NULL")]
		public bool IsHidden
		{
			get
			{
				return this._IsHidden;
			}
			set
			{
				if ((this._IsHidden != value))
				{
					this.OnIsHiddenChanging(value);
					this.SendPropertyChanging();
					this._IsHidden = value;
					this.SendPropertyChanged("IsHidden");
					this.OnIsHiddenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHaveData", DbType="Bit NOT NULL")]
		public bool IsHaveData
		{
			get
			{
				return this._IsHaveData;
			}
			set
			{
				if ((this._IsHaveData != value))
				{
					this.OnIsHaveDataChanging(value);
					this.SendPropertyChanging();
					this._IsHaveData = value;
					this.SendPropertyChanged("IsHaveData");
					this.OnIsHaveDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssuerID", DbType="Int")]
		public System.Nullable<int> IssuerID
		{
			get
			{
				return this._IssuerID;
			}
			set
			{
				if ((this._IssuerID != value))
				{
					this.OnIssuerIDChanging(value);
					this.SendPropertyChanging();
					this._IssuerID = value;
					this.SendPropertyChanged("IssuerID");
					this.OnIssuerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_BANK_W_AGG_COMP", Storage="_W_AGG_COMPs", ThisKey="BankID", OtherKey="BankID")]
		public EntitySet<W_AGG_COMP> W_AGG_COMPs
		{
			get
			{
				return this._W_AGG_COMPs;
			}
			set
			{
				this._W_AGG_COMPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_W_AGG_COMPs(W_AGG_COMP entity)
		{
			this.SendPropertyChanging();
			entity.A_BANK = this;
		}
		
		private void detach_W_AGG_COMPs(W_AGG_COMP entity)
		{
			this.SendPropertyChanging();
			entity.A_BANK = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_AGGS")]
	public partial class A_AGG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AggID;
		
		private string _FullName;
		
		private string _FullNameRUS;
		
		private string _FullNameENG;
		
		private bool _IsHidden;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAggIDChanging(int value);
    partial void OnAggIDChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnFullNameRUSChanging(string value);
    partial void OnFullNameRUSChanged();
    partial void OnFullNameENGChanging(string value);
    partial void OnFullNameENGChanged();
    partial void OnIsHiddenChanging(bool value);
    partial void OnIsHiddenChanged();
    #endregion
		
		public A_AGG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AggID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AggID
		{
			get
			{
				return this._AggID;
			}
			set
			{
				if ((this._AggID != value))
				{
					this.OnAggIDChanging(value);
					this.SendPropertyChanging();
					this._AggID = value;
					this.SendPropertyChanged("AggID");
					this.OnAggIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameRUS", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FullNameRUS
		{
			get
			{
				return this._FullNameRUS;
			}
			set
			{
				if ((this._FullNameRUS != value))
				{
					this.OnFullNameRUSChanging(value);
					this.SendPropertyChanging();
					this._FullNameRUS = value;
					this.SendPropertyChanged("FullNameRUS");
					this.OnFullNameRUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullNameENG", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FullNameENG
		{
			get
			{
				return this._FullNameENG;
			}
			set
			{
				if ((this._FullNameENG != value))
				{
					this.OnFullNameENGChanging(value);
					this.SendPropertyChanging();
					this._FullNameENG = value;
					this.SendPropertyChanged("FullNameENG");
					this.OnFullNameENGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHidden", DbType="Bit NOT NULL")]
		public bool IsHidden
		{
			get
			{
				return this._IsHidden;
			}
			set
			{
				if ((this._IsHidden != value))
				{
					this.OnIsHiddenChanging(value);
					this.SendPropertyChanging();
					this._IsHidden = value;
					this.SendPropertyChanged("IsHidden");
					this.OnIsHiddenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_BANKS_ALL")]
	public partial class A_BANKS_ALL
	{
		
		private int _BankID;
		
		private string _Name;
		
		private string _NameRus;
		
		private string _NameEng;
		
		private System.Nullable<int> _BankIDC1;
		
		private System.Nullable<int> _BankIDC2;
		
		public A_BANKS_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankID", DbType="Int NOT NULL")]
		public int BankID
		{
			get
			{
				return this._BankID;
			}
			set
			{
				if ((this._BankID != value))
				{
					this._BankID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRus", DbType="NVarChar(150)")]
		public string NameRus
		{
			get
			{
				return this._NameRus;
			}
			set
			{
				if ((this._NameRus != value))
				{
					this._NameRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEng", DbType="NVarChar(150)")]
		public string NameEng
		{
			get
			{
				return this._NameEng;
			}
			set
			{
				if ((this._NameEng != value))
				{
					this._NameEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankIDC1", DbType="Int")]
		public System.Nullable<int> BankIDC1
		{
			get
			{
				return this._BankIDC1;
			}
			set
			{
				if ((this._BankIDC1 != value))
				{
					this._BankIDC1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankIDC2", DbType="Int")]
		public System.Nullable<int> BankIDC2
		{
			get
			{
				return this._BankIDC2;
			}
			set
			{
				if ((this._BankIDC2 != value))
				{
					this._BankIDC2 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_VIEWITEMS_ALL")]
	public partial class A_VIEWITEMS_ALL
	{
		
		private int _ViewID;
		
		private string _ViewNameRus;
		
		private string _ViewNameEng;
		
		private int _Form;
		
		private int _Expandable;
		
		private System.Nullable<int> _ViewItemID;
		
		private string _Ticker;
		
		private string _NameRus;
		
		private string _NameEng;
		
		private bool _IsWithSub;
		
		private System.Nullable<int> _AggItemID;
		
		private System.Nullable<bool> _IsRatio;
		
		private System.Nullable<int> _LevelDepth;
		
		public A_VIEWITEMS_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewID", DbType="Int NOT NULL")]
		public int ViewID
		{
			get
			{
				return this._ViewID;
			}
			set
			{
				if ((this._ViewID != value))
				{
					this._ViewID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewNameRus", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ViewNameRus
		{
			get
			{
				return this._ViewNameRus;
			}
			set
			{
				if ((this._ViewNameRus != value))
				{
					this._ViewNameRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewNameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ViewNameEng
		{
			get
			{
				return this._ViewNameEng;
			}
			set
			{
				if ((this._ViewNameEng != value))
				{
					this._ViewNameEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="Int NOT NULL")]
		public int Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this._Form = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expandable", DbType="Int NOT NULL")]
		public int Expandable
		{
			get
			{
				return this._Expandable;
			}
			set
			{
				if ((this._Expandable != value))
				{
					this._Expandable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewItemID", DbType="Int")]
		public System.Nullable<int> ViewItemID
		{
			get
			{
				return this._ViewItemID;
			}
			set
			{
				if ((this._ViewItemID != value))
				{
					this._ViewItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="NVarChar(30)")]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this._Ticker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRus", DbType="NVarChar(200)")]
		public string NameRus
		{
			get
			{
				return this._NameRus;
			}
			set
			{
				if ((this._NameRus != value))
				{
					this._NameRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEng", DbType="NVarChar(200)")]
		public string NameEng
		{
			get
			{
				return this._NameEng;
			}
			set
			{
				if ((this._NameEng != value))
				{
					this._NameEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWithSub", DbType="Bit NOT NULL")]
		public bool IsWithSub
		{
			get
			{
				return this._IsWithSub;
			}
			set
			{
				if ((this._IsWithSub != value))
				{
					this._IsWithSub = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AggItemID", DbType="Int")]
		public System.Nullable<int> AggItemID
		{
			get
			{
				return this._AggItemID;
			}
			set
			{
				if ((this._AggItemID != value))
				{
					this._AggItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRatio", DbType="Bit")]
		public System.Nullable<bool> IsRatio
		{
			get
			{
				return this._IsRatio;
			}
			set
			{
				if ((this._IsRatio != value))
				{
					this._IsRatio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelDepth", DbType="Int")]
		public System.Nullable<int> LevelDepth
		{
			get
			{
				return this._LevelDepth;
			}
			set
			{
				if ((this._LevelDepth != value))
				{
					this._LevelDepth = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_F101_TOCURITEMS")]
	public partial class A_F101_TOCURITEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TOCurItemID;
		
		private string _Ticker;
		
		private bool _IsRatio;
		
		private string _NameRus;
		
		private string _NameEng;
		
		private string _WebRus;
		
		private string _WebEng;
		
		private int _OrderNum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTOCurItemIDChanging(int value);
    partial void OnTOCurItemIDChanged();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    partial void OnIsRatioChanging(bool value);
    partial void OnIsRatioChanged();
    partial void OnNameRusChanging(string value);
    partial void OnNameRusChanged();
    partial void OnNameEngChanging(string value);
    partial void OnNameEngChanged();
    partial void OnWebRusChanging(string value);
    partial void OnWebRusChanged();
    partial void OnWebEngChanging(string value);
    partial void OnWebEngChanged();
    partial void OnOrderNumChanging(int value);
    partial void OnOrderNumChanged();
    #endregion
		
		public A_F101_TOCURITEM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOCurItemID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TOCurItemID
		{
			get
			{
				return this._TOCurItemID;
			}
			set
			{
				if ((this._TOCurItemID != value))
				{
					this.OnTOCurItemIDChanging(value);
					this.SendPropertyChanging();
					this._TOCurItemID = value;
					this.SendPropertyChanged("TOCurItemID");
					this.OnTOCurItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRatio", DbType="Bit NOT NULL")]
		public bool IsRatio
		{
			get
			{
				return this._IsRatio;
			}
			set
			{
				if ((this._IsRatio != value))
				{
					this.OnIsRatioChanging(value);
					this.SendPropertyChanging();
					this._IsRatio = value;
					this.SendPropertyChanged("IsRatio");
					this.OnIsRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRus", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NameRus
		{
			get
			{
				return this._NameRus;
			}
			set
			{
				if ((this._NameRus != value))
				{
					this.OnNameRusChanging(value);
					this.SendPropertyChanging();
					this._NameRus = value;
					this.SendPropertyChanged("NameRus");
					this.OnNameRusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NameEng
		{
			get
			{
				return this._NameEng;
			}
			set
			{
				if ((this._NameEng != value))
				{
					this.OnNameEngChanging(value);
					this.SendPropertyChanging();
					this._NameEng = value;
					this.SendPropertyChanged("NameEng");
					this.OnNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebRus", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string WebRus
		{
			get
			{
				return this._WebRus;
			}
			set
			{
				if ((this._WebRus != value))
				{
					this.OnWebRusChanging(value);
					this.SendPropertyChanging();
					this._WebRus = value;
					this.SendPropertyChanged("WebRus");
					this.OnWebRusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebEng", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string WebEng
		{
			get
			{
				return this._WebEng;
			}
			set
			{
				if ((this._WebEng != value))
				{
					this.OnWebEngChanging(value);
					this.SendPropertyChanging();
					this._WebEng = value;
					this.SendPropertyChanged("WebEng");
					this.OnWebEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNum", DbType="Int NOT NULL")]
		public int OrderNum
		{
			get
			{
				return this._OrderNum;
			}
			set
			{
				if ((this._OrderNum != value))
				{
					this.OnOrderNumChanging(value);
					this.SendPropertyChanging();
					this._OrderNum = value;
					this.SendPropertyChanged("OrderNum");
					this.OnOrderNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_VIEWITEMS_COMPARE")]
	public partial class A_VIEWITEMS_COMPARE
	{
		
		private int _ViewID;
		
		private string _ViewNameRus;
		
		private string _ViewNameEng;
		
		private int _ViewItemID;
		
		private string _Ticker;
		
		private System.Nullable<int> _Form;
		
		private int _IsRatio;
		
		private int _IsHeader;
		
		private System.Nullable<int> _AggItemID;
		
		private System.Nullable<bool> _IsCollapsed;
		
		private int _LevelID;
		
		private string _NameRus;
		
		private string _NameEng;
		
		private string _ColumnName;
		
		public A_VIEWITEMS_COMPARE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewID", DbType="Int NOT NULL")]
		public int ViewID
		{
			get
			{
				return this._ViewID;
			}
			set
			{
				if ((this._ViewID != value))
				{
					this._ViewID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewNameRus", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ViewNameRus
		{
			get
			{
				return this._ViewNameRus;
			}
			set
			{
				if ((this._ViewNameRus != value))
				{
					this._ViewNameRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewNameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ViewNameEng
		{
			get
			{
				return this._ViewNameEng;
			}
			set
			{
				if ((this._ViewNameEng != value))
				{
					this._ViewNameEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewItemID", DbType="Int NOT NULL")]
		public int ViewItemID
		{
			get
			{
				return this._ViewItemID;
			}
			set
			{
				if ((this._ViewItemID != value))
				{
					this._ViewItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="NVarChar(30)")]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this._Ticker = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="Int")]
		public System.Nullable<int> Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this._Form = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRatio", DbType="Int NOT NULL")]
		public int IsRatio
		{
			get
			{
				return this._IsRatio;
			}
			set
			{
				if ((this._IsRatio != value))
				{
					this._IsRatio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHeader", DbType="Int NOT NULL")]
		public int IsHeader
		{
			get
			{
				return this._IsHeader;
			}
			set
			{
				if ((this._IsHeader != value))
				{
					this._IsHeader = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AggItemID", DbType="Int")]
		public System.Nullable<int> AggItemID
		{
			get
			{
				return this._AggItemID;
			}
			set
			{
				if ((this._AggItemID != value))
				{
					this._AggItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCollapsed", DbType="Bit")]
		public System.Nullable<bool> IsCollapsed
		{
			get
			{
				return this._IsCollapsed;
			}
			set
			{
				if ((this._IsCollapsed != value))
				{
					this._IsCollapsed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelID", DbType="Int NOT NULL")]
		public int LevelID
		{
			get
			{
				return this._LevelID;
			}
			set
			{
				if ((this._LevelID != value))
				{
					this._LevelID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRus", DbType="NVarChar(200)")]
		public string NameRus
		{
			get
			{
				return this._NameRus;
			}
			set
			{
				if ((this._NameRus != value))
				{
					this._NameRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEng", DbType="NVarChar(200)")]
		public string NameEng
		{
			get
			{
				return this._NameEng;
			}
			set
			{
				if ((this._NameEng != value))
				{
					this._NameEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnName", DbType="NVarChar(30)")]
		public string ColumnName
		{
			get
			{
				return this._ColumnName;
			}
			set
			{
				if ((this._ColumnName != value))
				{
					this._ColumnName = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_2X2CHARTS_VIEW")]
	public partial class A_2X2CHARTS_VIEW
	{
		
		private int _ChartID;
		
		private string _NameRus;
		
		private string _NameEng;
		
		private int _X_FormID;
		
		private int _X_AggItemID;
		
		private decimal _X_MaxValue;
		
		private string _X_AggItemNameRus;
		
		private string _X_AggItemNameEng;
		
		private int _Y_FormID;
		
		private int _Y_AggItemID;
		
		private decimal _Y_MaxValue;
		
		private string _Y_AggItemNameRus;
		
		private string _Y_AggItemNameEng;
		
		public A_2X2CHARTS_VIEW()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChartID", DbType="Int NOT NULL")]
		public int ChartID
		{
			get
			{
				return this._ChartID;
			}
			set
			{
				if ((this._ChartID != value))
				{
					this._ChartID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRus", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NameRus
		{
			get
			{
				return this._NameRus;
			}
			set
			{
				if ((this._NameRus != value))
				{
					this._NameRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string NameEng
		{
			get
			{
				return this._NameEng;
			}
			set
			{
				if ((this._NameEng != value))
				{
					this._NameEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X_FormID", DbType="Int NOT NULL")]
		public int X_FormID
		{
			get
			{
				return this._X_FormID;
			}
			set
			{
				if ((this._X_FormID != value))
				{
					this._X_FormID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X_AggItemID", DbType="Int NOT NULL")]
		public int X_AggItemID
		{
			get
			{
				return this._X_AggItemID;
			}
			set
			{
				if ((this._X_AggItemID != value))
				{
					this._X_AggItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X_MaxValue", DbType="Decimal(28,8) NOT NULL")]
		public decimal X_MaxValue
		{
			get
			{
				return this._X_MaxValue;
			}
			set
			{
				if ((this._X_MaxValue != value))
				{
					this._X_MaxValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X_AggItemNameRus", DbType="NVarChar(403)")]
		public string X_AggItemNameRus
		{
			get
			{
				return this._X_AggItemNameRus;
			}
			set
			{
				if ((this._X_AggItemNameRus != value))
				{
					this._X_AggItemNameRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_X_AggItemNameEng", DbType="NVarChar(403)")]
		public string X_AggItemNameEng
		{
			get
			{
				return this._X_AggItemNameEng;
			}
			set
			{
				if ((this._X_AggItemNameEng != value))
				{
					this._X_AggItemNameEng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y_FormID", DbType="Int NOT NULL")]
		public int Y_FormID
		{
			get
			{
				return this._Y_FormID;
			}
			set
			{
				if ((this._Y_FormID != value))
				{
					this._Y_FormID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y_AggItemID", DbType="Int NOT NULL")]
		public int Y_AggItemID
		{
			get
			{
				return this._Y_AggItemID;
			}
			set
			{
				if ((this._Y_AggItemID != value))
				{
					this._Y_AggItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y_MaxValue", DbType="Decimal(28,8) NOT NULL")]
		public decimal Y_MaxValue
		{
			get
			{
				return this._Y_MaxValue;
			}
			set
			{
				if ((this._Y_MaxValue != value))
				{
					this._Y_MaxValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y_AggItemNameRus", DbType="NVarChar(403)")]
		public string Y_AggItemNameRus
		{
			get
			{
				return this._Y_AggItemNameRus;
			}
			set
			{
				if ((this._Y_AggItemNameRus != value))
				{
					this._Y_AggItemNameRus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y_AggItemNameEng", DbType="NVarChar(403)")]
		public string Y_AggItemNameEng
		{
			get
			{
				return this._Y_AggItemNameEng;
			}
			set
			{
				if ((this._Y_AggItemNameEng != value))
				{
					this._Y_AggItemNameEng = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.W_AGG_COMP")]
	public partial class W_AGG_COMP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AggID;
		
		private int _BankID;
		
		private bool _F101IsWithTO;
		
		private bool _F134;
		
		private EntityRef<A_BANK> _A_BANK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAggIDChanging(int value);
    partial void OnAggIDChanged();
    partial void OnBankIDChanging(int value);
    partial void OnBankIDChanged();
    partial void OnF101IsWithTOChanging(bool value);
    partial void OnF101IsWithTOChanged();
    partial void OnF134Changing(bool value);
    partial void OnF134Changed();
    #endregion
		
		public W_AGG_COMP()
		{
			this._A_BANK = default(EntityRef<A_BANK>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AggID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AggID
		{
			get
			{
				return this._AggID;
			}
			set
			{
				if ((this._AggID != value))
				{
					this.OnAggIDChanging(value);
					this.SendPropertyChanging();
					this._AggID = value;
					this.SendPropertyChanged("AggID");
					this.OnAggIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BankID
		{
			get
			{
				return this._BankID;
			}
			set
			{
				if ((this._BankID != value))
				{
					if (this._A_BANK.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBankIDChanging(value);
					this.SendPropertyChanging();
					this._BankID = value;
					this.SendPropertyChanged("BankID");
					this.OnBankIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F101IsWithTO", DbType="Bit NOT NULL")]
		public bool F101IsWithTO
		{
			get
			{
				return this._F101IsWithTO;
			}
			set
			{
				if ((this._F101IsWithTO != value))
				{
					this.OnF101IsWithTOChanging(value);
					this.SendPropertyChanging();
					this._F101IsWithTO = value;
					this.SendPropertyChanged("F101IsWithTO");
					this.OnF101IsWithTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F134", DbType="Bit NOT NULL")]
		public bool F134
		{
			get
			{
				return this._F134;
			}
			set
			{
				if ((this._F134 != value))
				{
					this.OnF134Changing(value);
					this.SendPropertyChanging();
					this._F134 = value;
					this.SendPropertyChanged("F134");
					this.OnF134Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_BANK_W_AGG_COMP", Storage="_A_BANK", ThisKey="BankID", OtherKey="BankID", IsForeignKey=true)]
		public A_BANK A_BANK
		{
			get
			{
				return this._A_BANK.Entity;
			}
			set
			{
				A_BANK previousValue = this._A_BANK.Entity;
				if (((previousValue != value) 
							|| (this._A_BANK.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._A_BANK.Entity = null;
						previousValue.W_AGG_COMPs.Remove(this);
					}
					this._A_BANK.Entity = value;
					if ((value != null))
					{
						value.W_AGG_COMPs.Add(this);
						this._BankID = value.BankID;
					}
					else
					{
						this._BankID = default(int);
					}
					this.SendPropertyChanged("A_BANK");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_VIEWS_BANKSPIC")]
	public partial class A_VIEWS_BANKSPIC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ViewID;
		
		private string _Ticker;
		
		private string _ViewNameRus;
		
		private string _ViewNameEng;
		
		private int _Form;
		
		private bool _IsHidden;
		
		private int _OrderNum;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnViewIDChanging(int value);
    partial void OnViewIDChanged();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    partial void OnViewNameRusChanging(string value);
    partial void OnViewNameRusChanged();
    partial void OnViewNameEngChanging(string value);
    partial void OnViewNameEngChanged();
    partial void OnFormChanging(int value);
    partial void OnFormChanged();
    partial void OnIsHiddenChanging(bool value);
    partial void OnIsHiddenChanged();
    partial void OnOrderNumChanging(int value);
    partial void OnOrderNumChanged();
    #endregion
		
		public A_VIEWS_BANKSPIC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ViewID
		{
			get
			{
				return this._ViewID;
			}
			set
			{
				if ((this._ViewID != value))
				{
					this.OnViewIDChanging(value);
					this.SendPropertyChanging();
					this._ViewID = value;
					this.SendPropertyChanged("ViewID");
					this.OnViewIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewNameRus", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ViewNameRus
		{
			get
			{
				return this._ViewNameRus;
			}
			set
			{
				if ((this._ViewNameRus != value))
				{
					this.OnViewNameRusChanging(value);
					this.SendPropertyChanging();
					this._ViewNameRus = value;
					this.SendPropertyChanged("ViewNameRus");
					this.OnViewNameRusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewNameEng", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string ViewNameEng
		{
			get
			{
				return this._ViewNameEng;
			}
			set
			{
				if ((this._ViewNameEng != value))
				{
					this.OnViewNameEngChanging(value);
					this.SendPropertyChanging();
					this._ViewNameEng = value;
					this.SendPropertyChanged("ViewNameEng");
					this.OnViewNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Form", DbType="Int NOT NULL")]
		public int Form
		{
			get
			{
				return this._Form;
			}
			set
			{
				if ((this._Form != value))
				{
					this.OnFormChanging(value);
					this.SendPropertyChanging();
					this._Form = value;
					this.SendPropertyChanged("Form");
					this.OnFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHidden", DbType="Bit NOT NULL")]
		public bool IsHidden
		{
			get
			{
				return this._IsHidden;
			}
			set
			{
				if ((this._IsHidden != value))
				{
					this.OnIsHiddenChanging(value);
					this.SendPropertyChanging();
					this._IsHidden = value;
					this.SendPropertyChanged("IsHidden");
					this.OnIsHiddenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNum", DbType="Int NOT NULL")]
		public int OrderNum
		{
			get
			{
				return this._OrderNum;
			}
			set
			{
				if ((this._OrderNum != value))
				{
					this.OnOrderNumChanging(value);
					this.SendPropertyChanging();
					this._OrderNum = value;
					this.SendPropertyChanged("OrderNum");
					this.OnOrderNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_DATE")]
	public partial class A_DATE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DateID;
		
		private System.DateTime _Date;
		
		private bool _IsQuartal;
		
		private bool _IsVisible;
		
		private bool _F101;
		
		private bool _F102;
		
		private bool _F123;
		
		private bool _F134;
		
		private bool _F135;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDateIDChanging(int value);
    partial void OnDateIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnIsQuartalChanging(bool value);
    partial void OnIsQuartalChanged();
    partial void OnIsVisibleChanging(bool value);
    partial void OnIsVisibleChanged();
    partial void OnF101Changing(bool value);
    partial void OnF101Changed();
    partial void OnF102Changing(bool value);
    partial void OnF102Changed();
    partial void OnF123Changing(bool value);
    partial void OnF123Changed();
    partial void OnF134Changing(bool value);
    partial void OnF134Changed();
    partial void OnF135Changing(bool value);
    partial void OnF135Changed();
    #endregion
		
		public A_DATE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DateID
		{
			get
			{
				return this._DateID;
			}
			set
			{
				if ((this._DateID != value))
				{
					this.OnDateIDChanging(value);
					this.SendPropertyChanging();
					this._DateID = value;
					this.SendPropertyChanged("DateID");
					this.OnDateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsQuartal", DbType="Bit NOT NULL")]
		public bool IsQuartal
		{
			get
			{
				return this._IsQuartal;
			}
			set
			{
				if ((this._IsQuartal != value))
				{
					this.OnIsQuartalChanging(value);
					this.SendPropertyChanging();
					this._IsQuartal = value;
					this.SendPropertyChanged("IsQuartal");
					this.OnIsQuartalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVisible", DbType="Bit NOT NULL")]
		public bool IsVisible
		{
			get
			{
				return this._IsVisible;
			}
			set
			{
				if ((this._IsVisible != value))
				{
					this.OnIsVisibleChanging(value);
					this.SendPropertyChanging();
					this._IsVisible = value;
					this.SendPropertyChanged("IsVisible");
					this.OnIsVisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F101", DbType="Bit NOT NULL")]
		public bool F101
		{
			get
			{
				return this._F101;
			}
			set
			{
				if ((this._F101 != value))
				{
					this.OnF101Changing(value);
					this.SendPropertyChanging();
					this._F101 = value;
					this.SendPropertyChanged("F101");
					this.OnF101Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F102", DbType="Bit NOT NULL")]
		public bool F102
		{
			get
			{
				return this._F102;
			}
			set
			{
				if ((this._F102 != value))
				{
					this.OnF102Changing(value);
					this.SendPropertyChanging();
					this._F102 = value;
					this.SendPropertyChanged("F102");
					this.OnF102Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F123", DbType="Bit NOT NULL")]
		public bool F123
		{
			get
			{
				return this._F123;
			}
			set
			{
				if ((this._F123 != value))
				{
					this.OnF123Changing(value);
					this.SendPropertyChanging();
					this._F123 = value;
					this.SendPropertyChanged("F123");
					this.OnF123Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F134", DbType="Bit NOT NULL")]
		public bool F134
		{
			get
			{
				return this._F134;
			}
			set
			{
				if ((this._F134 != value))
				{
					this.OnF134Changing(value);
					this.SendPropertyChanging();
					this._F134 = value;
					this.SendPropertyChanged("F134");
					this.OnF134Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F135", DbType="Bit NOT NULL")]
		public bool F135
		{
			get
			{
				return this._F135;
			}
			set
			{
				if ((this._F135 != value))
				{
					this.OnF135Changing(value);
					this.SendPropertyChanging();
					this._F135 = value;
					this.SendPropertyChanged("F135");
					this.OnF135Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_VIEWITEMS")]
	public partial class A_VIEWITEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ViewID;
		
		private int _ViewItemID;
		
		private int _LevelDepth;
		
		private bool _IsWithSub;
		
		private System.Nullable<int> _AggItemID;
		
		private string _HeaderNameRus;
		
		private string _HeaderNameEng;
		
		private System.Nullable<int> _ParID;
		
		private EntityRef<A_PARAM> _A_PARAM;
		
		private EntityRef<A_VIEW> _A_VIEW;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnViewIDChanging(int value);
    partial void OnViewIDChanged();
    partial void OnViewItemIDChanging(int value);
    partial void OnViewItemIDChanged();
    partial void OnLevelDepthChanging(int value);
    partial void OnLevelDepthChanged();
    partial void OnIsWithSubChanging(bool value);
    partial void OnIsWithSubChanged();
    partial void OnAggItemIDChanging(System.Nullable<int> value);
    partial void OnAggItemIDChanged();
    partial void OnHeaderNameRusChanging(string value);
    partial void OnHeaderNameRusChanged();
    partial void OnHeaderNameEngChanging(string value);
    partial void OnHeaderNameEngChanged();
    partial void OnParIDChanging(System.Nullable<int> value);
    partial void OnParIDChanged();
    #endregion
		
		public A_VIEWITEM()
		{
			this._A_PARAM = default(EntityRef<A_PARAM>);
			this._A_VIEW = default(EntityRef<A_VIEW>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ViewID
		{
			get
			{
				return this._ViewID;
			}
			set
			{
				if ((this._ViewID != value))
				{
					if (this._A_VIEW.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnViewIDChanging(value);
					this.SendPropertyChanging();
					this._ViewID = value;
					this.SendPropertyChanged("ViewID");
					this.OnViewIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewItemID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ViewItemID
		{
			get
			{
				return this._ViewItemID;
			}
			set
			{
				if ((this._ViewItemID != value))
				{
					this.OnViewItemIDChanging(value);
					this.SendPropertyChanging();
					this._ViewItemID = value;
					this.SendPropertyChanged("ViewItemID");
					this.OnViewItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LevelDepth", DbType="Int NOT NULL")]
		public int LevelDepth
		{
			get
			{
				return this._LevelDepth;
			}
			set
			{
				if ((this._LevelDepth != value))
				{
					this.OnLevelDepthChanging(value);
					this.SendPropertyChanging();
					this._LevelDepth = value;
					this.SendPropertyChanged("LevelDepth");
					this.OnLevelDepthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsWithSub", DbType="Bit NOT NULL")]
		public bool IsWithSub
		{
			get
			{
				return this._IsWithSub;
			}
			set
			{
				if ((this._IsWithSub != value))
				{
					this.OnIsWithSubChanging(value);
					this.SendPropertyChanging();
					this._IsWithSub = value;
					this.SendPropertyChanged("IsWithSub");
					this.OnIsWithSubChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AggItemID", DbType="Int")]
		public System.Nullable<int> AggItemID
		{
			get
			{
				return this._AggItemID;
			}
			set
			{
				if ((this._AggItemID != value))
				{
					this.OnAggItemIDChanging(value);
					this.SendPropertyChanging();
					this._AggItemID = value;
					this.SendPropertyChanged("AggItemID");
					this.OnAggItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeaderNameRus", DbType="NVarChar(200)")]
		public string HeaderNameRus
		{
			get
			{
				return this._HeaderNameRus;
			}
			set
			{
				if ((this._HeaderNameRus != value))
				{
					this.OnHeaderNameRusChanging(value);
					this.SendPropertyChanging();
					this._HeaderNameRus = value;
					this.SendPropertyChanged("HeaderNameRus");
					this.OnHeaderNameRusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeaderNameEng", DbType="NVarChar(200)")]
		public string HeaderNameEng
		{
			get
			{
				return this._HeaderNameEng;
			}
			set
			{
				if ((this._HeaderNameEng != value))
				{
					this.OnHeaderNameEngChanging(value);
					this.SendPropertyChanging();
					this._HeaderNameEng = value;
					this.SendPropertyChanged("HeaderNameEng");
					this.OnHeaderNameEngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParID", DbType="Int")]
		public System.Nullable<int> ParID
		{
			get
			{
				return this._ParID;
			}
			set
			{
				if ((this._ParID != value))
				{
					if (this._A_PARAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParIDChanging(value);
					this.SendPropertyChanging();
					this._ParID = value;
					this.SendPropertyChanged("ParID");
					this.OnParIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_PARAM_A_VIEWITEM", Storage="_A_PARAM", ThisKey="ParID", OtherKey="ParID", IsForeignKey=true)]
		public A_PARAM A_PARAM
		{
			get
			{
				return this._A_PARAM.Entity;
			}
			set
			{
				A_PARAM previousValue = this._A_PARAM.Entity;
				if (((previousValue != value) 
							|| (this._A_PARAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._A_PARAM.Entity = null;
						previousValue.A_VIEWITEMs.Remove(this);
					}
					this._A_PARAM.Entity = value;
					if ((value != null))
					{
						value.A_VIEWITEMs.Add(this);
						this._ParID = value.ParID;
					}
					else
					{
						this._ParID = default(Nullable<int>);
					}
					this.SendPropertyChanged("A_PARAM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="A_VIEW_A_VIEWITEM", Storage="_A_VIEW", ThisKey="ViewID", OtherKey="ViewID", IsForeignKey=true)]
		public A_VIEW A_VIEW
		{
			get
			{
				return this._A_VIEW.Entity;
			}
			set
			{
				A_VIEW previousValue = this._A_VIEW.Entity;
				if (((previousValue != value) 
							|| (this._A_VIEW.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._A_VIEW.Entity = null;
						previousValue.A_VIEWITEMs.Remove(this);
					}
					this._A_VIEW.Entity = value;
					if ((value != null))
					{
						value.A_VIEWITEMs.Add(this);
						this._ViewID = value.ViewID;
					}
					else
					{
						this._ViewID = default(int);
					}
					this.SendPropertyChanged("A_VIEW");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
